### ISSUE TITLE
你好请问gfwlist模式是怎么生成的。/etc/config下面没有gfwlit文件啊？

### ISSUE THREAD

**Issue by ztechie** [crwnet/openwrt-15.05-move-to-openwrt-#2]
你好请问gfwlist模式是怎么生成的。/etc/config下面没有gfwlit文件啊？

**Comment by crwnet** [comment]
在/etc/config/dnsmasq下

**Comment by ztechie** [comment]
在etc/config/dnsmasq/里面上传了gfwlist.dns。内容如下
server=/.4tern.com/127.0.0.1#5300
ipset=/.4tern.com/vpn
server=/.85.17.73.31/127.0.0.1#5300
ipset=/.85.17.73.31/vpn
server=/.adorama.com/127.0.0.1#5300
ipset=/.adorama.com/vpn
server=/.agnesb.fr/127.0.0.1#5300
ipset=/.agnesb.fr/vpn
server=/.akiba-web.com/127.0.0.1#5300
ipset=/.akiba-web.com/vpn
server=/.alien-ufos.com/127.0.0.1#5300
ipset=/.alien-ufos.com/vpn
server=/.altrec.com/127.0.0.1#5300
ipset=/.altrec.com/vpn
server=/.arena.taipei/127.0.0.1#5300
ipset=/.arena.taipei/vpn
server=/.asianspiss.com/127.0.0.1#5300
ipset=/.asianspiss.com/vpn
server=/.athenaeizou.com/127.0.0.1#5300
ipset=/.athenaeizou.com/vpn
server=/.azubu.tv/127.0.0.1#5300
ipset=/.azubu.tv/vpn
server=/.barracuda.com/127.0.0.1#5300
ipset=/.barracuda.com/vpn
server=/.beeg.com/127.0.0.1#5300
不知为何还是不生效，其他模式没问题

**Comment by ztechie** [comment]
Sat Oct 29 06:01:35 2016 daemon.crit dnsmasq[12966]: recompile with HAVE_IPSET defined to enable ipset directives at line 2 of /etc/config/dnsmasq/gfwlist.dns
Sat Oct 29 06:01:35 2016 daemon.crit dnsmasq[12966]: FAILED to start up

**Comment by w01230** [comment]
You should get a "full dnsmasq", you can  find it in make file.

**Comment by ztechie** [comment]
非常感谢已经移植到4300
