### ISSUE TITLE
能否在图形界面上添加一个SOCKS5代理

### ISSUE THREAD

**Issue by ztechie** [crwnet/openwrt-15.05-move-to-openwrt-#3]
![image](https://cloud.githubusercontent.com/assets/9046704/19997286/58684768-a2a0-11e6-9e43-23570bd1a13e.png)

**Comment by ztechie** [comment]
非常感谢

**Comment by crwnet** [comment]
其实选择dns2socks方案的话默认就有的，端口是固定1081
